version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=roshan_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:pass@db:5432/roshan_db