# Generated by Django 5.2.4 on 2026-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سند')),
                ('content', models.TextField(verbose_name='متن کامل محتوا')),
                ('tags', models.CharField(help_text='با کاما جدا کنید', max_length=255, verbose_name='برچسب\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='پرسش کاربر')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ سیستم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('related_documents', models.ManyToManyField(blank=True, to='knowledge_base.document', verbose_name='اسناد مرتبط')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'پرسش\u200cها و پاسخ\u200cها',
            },
        ),
    ]
